# -*- coding: utf-8 -*-
"""RutendraBiswal_Capstone_python notebook_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFTI4C7NZCen_NsfLEe7xwtNrlXAkipp

## Rutendra Biswal_Capstone_Project
"""

# !pip install pyforest

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

file_path = "Bank_Stability_Dataset.csv"
df = pd.read_csv(file_path)

df.head()

df.info()

df.shape

df.describe()

#Check for missing values
print(df.isnull().sum())

"""#Cleaning"""

# Step 2: Data Cleaning
# # Assuming df is your DataFrame
mode_value = df['Went_Defunct'].mode()[0]  # Get the mode of the Went_Defunct column
df['Went_Defunct'].fillna(mode_value, inplace=True)  # Fill NaN values with the mode

df_clean = df['Went_Defunct'].mode()[0]  # Get the first mode value

# df_clean= df.dropna(subset=['Went_Defunct'])
mode_value = df['Went_Defunct'].mode()[0]  # Get the mode of the Went_Defunct column
df['Went_Defunct'].fillna(mode_value, inplace=True)  # Fill NaN values with the mode
df_clean = df  # Assign the modified DataFrame to df_clean
df_clean.shape

df_clean.isnull().sum()

df_clean= df_clean.drop_duplicates()
print(df_clean['Went_Defunct'].value_counts())

# Step 3: Encode the target variable 'Went_Defunct'-{"yes":1,"NO"-0}

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_clean['Went_Defunct'] = label_encoder.fit_transform(df_clean['Went_Defunct'])

"""# EDA"""

#heat map
correlation = df_clean.select_dtypes(include=["int","float"]).corr()
sns.heatmap(correlation, xticklabels=correlation.columns, yticklabels=correlation.columns,cmap="Blues", annot=True)
plt.show()

#scatter plot
sns.pairplot(df_clean)

#Histogram of CAR
plt.hist(df_clean['Capital_Adequacy_Ratio'], bins=10)
plt.xlabel('Capital Adequacy Ratio')
plt.ylabel('Frequency')
plt.title('Histogram of Capital Adequacy Ratio')
plt.show()

# Loop through each column and create a box plot
for column in df_clean.columns:
    plt.figure(figsize=(8, 6))
    sns.boxplot(y=df_clean[column])
    plt.title(f'Box Plot of {column}')
    plt.ylabel(column)
    plt.show()

# Create the countplot
plt.figure(figsize=(10, 6))  # Adjust figure size as needed
sns.countplot(x='Went_Defunct', data=df_clean)
plt.title('Count of Went Defunct')
plt.xlabel('Went Defunct (0 or 1)')
plt.ylabel('Count')
plt.show()

sns.histplot(data=df_clean, x='Liquidity_Coverage_Ratio', hue='Went_Defunct', kde=True)
plt.title("Liquidity Ratio Distribution by Bank StabiLity")
plt. title("Liquidity Ratio by Stability")

"""#ML

"""

#to find categorical columns and numerical columns
categorial_col = [col for col in df_clean.columns if df_clean[col].dtype == 'object']

numerical_col = [col for col in df_clean.columns if df_clean[col].dtype != 'object']
print('Categorical columns :',categorial_col)
print('Numerical columns :',numerical_col)

"""#Out-layer removal"""

#z-score
def remove_outliers_zscore(df, columns, threshold=3):
    """Remove outliers using the Z-score method."""
    z = np.abs((df[columns] - df[columns].mean()) / df[columns].std())
    df_filtered = df[(z < threshold).all(axis=1)]
    return df_filtered

# Assuming numerical_col is defined somewhere
numerical_col = ['Capital_Adequacy_Ratio', 'Non_Performing_Loans_Ratio', 'Liquidity_Coverage_Ratio',
                 'Return_on_Assets', 'Loan_to_Deposit_Ratio', 'Net_Interest_Margin',
                 'Operational_Efficiency_Ratio']

# Remove outliers using the Z-score method
bank_cleaned_zscore = remove_outliers_zscore(df_clean, numerical_col)

# Check the shape of the cleaned dataset after Z-score
original_shape = df_clean.shape
cleaned_shape_zscore = bank_cleaned_zscore.shape
print("Original Shape:", original_shape)
print("Shape after Z-score Outlier Removal:", cleaned_shape_zscore)

# Assuming 'df_clean' is your DataFrame
# Separate features (X) and target (y)
X = df_clean.drop('Went_Defunct', axis=1)
y = df_clean['Went_Defunct']

"""#Level Encoding"""

from sklearn.preprocessing import LabelEncoder

# Apply Label Encoding to categorical features
label_encoders = {}

for column in X.select_dtypes(include=['category', 'object']).columns:
    label_encoders[column] = LabelEncoder()
    X[column] = label_encoders[column].fit_transform(X[column])

"""#Train-Test"""

from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier

"""##Random forest"""

# Initialize and train a Random Forest Classifier
rf_clf = RandomForestClassifier(random_state=42)
rf_clf.fit(X_train, y_train)

rf_y_pred = rf_clf.predict(X_test)
X_train.shape

from sklearn.metrics import accuracy_score

rf_accuracy = accuracy_score(y_test, rf_y_pred)
print(f"Random Forest Accuracy: {rf_accuracy}")

#Confusion matrix
from sklearn.metrics import confusion_matrix

m = confusion_matrix(y_test,rf_y_pred)
print (m)
print ("Accuracy of prediction:", 100*round((m[0,0]+m[1,1]) / m.sum(),3),"%")

"""##Logistic regression"""

#logistic regression model
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score

# Create a logistic regression model with class weights
model = LogisticRegression(class_weight={0: 60, 1: 1}, solver='liblinear', max_iter=1000)

# Train the model
model.fit(X_train, y_train)

# Predict on the test set
y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

# Evaluate the model
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print ROC AUC Score
print("ROC AUC Score:", roc_auc_score(y_test, y_proba))

import pickle

#Download the ppickle file of Logistic regression
with open ("logistic_model.pkl", "wb") as f:
 pickle.dump (model, f)

##Download the ppickle file of Random-Forest

with open("random_forest_model.pkl", "wb") as f:
    pickle.dump(rf_clf, f)

